server:
  port: 9090

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(PDvfxxu/9vhEwuWJWF7MbiwA/2VRf0g97nbYe2mhu2WuHvy62IuXKXqJkWSQOel1Wpl/aAKHEDkPpq8FrOpjpJLsDL+raA7AMfLem4TmIi0NZAekhk4p3t81R1OOI9lbqvwB1+5mymE=)
    username: ENC(H4Kfme/f7MpOeUDKA07xsYyblqV8YqvU1UsXspkQspUwtzUmRA0V6g==)
    password: ENC(7XrqW8R9ldBRlTWH7AoeT7TSR0YiCHOB)

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: true

  data:
    web:
      pageable:
        default-page-size: 10

decorator:
  datasource:
    p6spy:
      enable-logging: true
      log-format: "%(sql)"

jasypt:
  encryptor:
    password: ${password}
